#
# Write a pkg-config pc file for given "name" with "decription"
# Arguments:
#   name: a library name (without "lib" prefix and "so" suffixes
#   desc: a desription string
#
# PKG_EXTRA_LIBS holds the libraries we link against internally (-lm, OpenMP,
# an LP solver). None of them appear in the installed headers, so for a shared
# build they belong in Libs.private, where only static consumers
# (pkg-config --static) pick them up. A static libvidstab cannot resolve them
# on its own, so there they have to stay in Libs.
macro (create_pkgconfig_file name desc)
    set(_pkgfname "${CMAKE_CURRENT_BINARY_DIR}/${name}.pc")
    message(STATUS "${name}: writing pkgconfig file ${_pkgfname}")

    set(_pkg_libs_private " ${PKG_EXTRA_LIBS}")
    if(BUILD_SHARED_LIBS)
      set(_pkg_libs "")
    else()
      set(_pkg_libs " ${PKG_EXTRA_LIBS}")
    endif()

    file(WRITE "${_pkgfname}" "# file generated by vid.stab cmake build
prefix=${CMAKE_INSTALL_PREFIX}
libdir=${CMAKE_INSTALL_FULL_LIBDIR}
includedir=${CMAKE_INSTALL_FULL_INCLUDEDIR}

Name: ${name}
Description: ${desc}
Version: ${VIDSTAB_VERSION}
Libs: -L\${libdir} -l${name}${_pkg_libs}
Libs.private:${_pkg_libs_private}
Cflags: -I\${includedir}

")

    install(FILES ${_pkgfname} DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig)
endmacro()
